org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Fabric - check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

# Mod
version=2.0.0
group=arsenic
archives_base_name=Arsenic

# Dependencies
discord_ipc_version=a8d6631cc90b25f1ede2178b99ad19d016f002a0
