package arsenic.runtime;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.commons.Remapper;
import org.objectweb.asm.commons.RemappingClassAdapter;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The names Minecraft has in the running game, for the client's SRG names. The client jar is built against SRG names,
 * which is what Forge runs. Vanilla runs Mojang's obfuscated (notch) names, and Lunar Client runs MCP names, so an
 * injected client is renamed as it loads ({@link #toRuntime}) and the hooks and reflective lookups go through here.
 *
 * Tables come from /inject-mappings.txt (generated by the build). This class must not touch Minecraft classes: the
 * injector's agent uses it from the system class loader too.
 */
public final class RuntimeNames {

    public enum Namespace {
        /** Forge: SRG names, same as the client jar. */
        SRG,
        /** Lunar Client and development games: MCP names. */
        MCP,
        /** Vanilla: Mojang's obfuscated names. */
        NOTCH
    }

    private static final String MC = "net/minecraft/";
    private static final byte[] MC_BYTES = MC.getBytes(StandardCharsets.ISO_8859_1);

    private static volatile RuntimeNames current = new RuntimeNames(Namespace.SRG, null);
    private static Tables tables;

    private final Namespace namespace;
    private final Tables t;
    /** Reads class files of non-Minecraft classes (the client's own) for their super types. */
    private final ClassLoader loader;
    private final Map<String, String[]> otherSupers = new ConcurrentHashMap<>();
    private final Map<String, String> resolved = new ConcurrentHashMap<>();

    private RuntimeNames(Namespace namespace, ClassLoader loader) {
        this.namespace = namespace;
        this.loader = loader;
        this.t = namespace == Namespace.SRG ? null : tables();
    }

    /** The names of the game this copy of the client runs in. SRG until the injector says otherwise. */
    public static RuntimeNames current() {
        return current;
    }

    public static RuntimeNames create(Namespace namespace, ClassLoader loader) {
        return new RuntimeNames(namespace, loader);
    }

    public static void setCurrent(RuntimeNames names) {
        current = names;
    }

    public Namespace namespace() {
        return namespace;
    }

    // ---- tables ----

    private static final class Tables {
        final Map<String, String> classToRuntime = new HashMap<>(); // srg -> notch
        final Map<String, String> classToSrg = new HashMap<>();     // notch -> srg
        final Map<String, String[]> supers = new HashMap<>();       // srg -> srg super types
        final Map<String, String> fields = new HashMap<>();         // "owner name" -> notch
        final Map<String, String> methods = new HashMap<>();        // "owner name desc" -> notch
        final Map<String, Set<String>> methodNames = new HashMap<>(); // "owner name" -> notch names (any desc)
        final Map<String, String> mcp = new HashMap<>();            // srg member name -> Lunar MCP name
        Map<String, String> fieldsBack, methodsBack;                 // built on first use
    }

    private static synchronized Tables tables() {
        if (tables != null)
            return tables;
        Tables t = new Tables();
        try (InputStream in = RuntimeNames.class.getResourceAsStream("/inject-mappings.txt")) {
            if (in == null)
                throw new IllegalStateException("inject-mappings.txt is missing from this build");
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] p = line.split(" ");
                switch (p[0]) {
                    case "C": {
                        t.classToRuntime.put(p[1], p[2]);
                        t.classToSrg.put(p[2], p[1]);
                        String[] supers = new String[p.length - 3];
                        System.arraycopy(p, 3, supers, 0, supers.length);
                        t.supers.put(p[1], supers);
                        break;
                    }
                    case "F":
                        t.fields.put(p[1] + ' ' + p[2], p[3]);
                        break;
                    case "M":
                        t.methods.put(p[1] + ' ' + p[2] + ' ' + p[3], p[4]);
                        t.methodNames.computeIfAbsent(p[1] + ' ' + p[2], k -> new HashSet<>()).add(p[4]);
                        break;
                    case "L":
                        t.mcp.put(p[1], p[2]);
                        break;
                }
            }
        } catch (IllegalStateException e) {
            throw e;
        } catch (Exception e) {
            throw new IllegalStateException("Could not read inject-mappings.txt", e);
        }
        tables = t;
        return t;
    }

    // ---- SRG -> runtime ----

    /** Runtime internal name of a class given by its SRG (= MCP) internal name. */
    public String mapClass(String srg) {
        if (namespace != Namespace.NOTCH || srg == null)
            return srg;
        if (srg.startsWith("[")) {
            return mapDesc(srg);
        }
        String notch = t.classToRuntime.get(srg);
        if (notch != null)
            return notch;
        // inner classes the table has no entry for keep their outer class's renaming
        int dollar = srg.lastIndexOf('$');
        if (dollar > 0 && t.classToRuntime.containsKey(srg.substring(0, dollar)))
            return mapClass(srg.substring(0, dollar)) + srg.substring(dollar);
        return srg;
    }

    /** SRG internal name of a runtime class. */
    public String unmapClass(String runtime) {
        if (namespace != Namespace.NOTCH || runtime == null)
            return runtime;
        String srg = t.classToSrg.get(runtime);
        return srg != null ? srg : runtime;
    }

    /** A field or method descriptor with its class names mapped. */
    public String mapDesc(String desc) {
        if (namespace != Namespace.NOTCH || desc.indexOf('L') < 0)
            return desc;
        StringBuilder sb = new StringBuilder(desc.length());
        for (int i = 0; i < desc.length(); i++) {
            char c = desc.charAt(i);
            sb.append(c);
            if (c == 'L') {
                int end = desc.indexOf(';', i);
                sb.append(mapClass(desc.substring(i + 1, end))).append(';');
                i = end;
            }
        }
        return sb.toString();
    }

    /** Runtime name of a field, looked up from {@code srgOwner} through its super types. */
    public String mapField(String srgOwner, String srgName) {
        switch (namespace) {
            case SRG:
                return srgName;
            case MCP:
                return mcpName(srgName);
            default:
                String key = "F " + srgOwner + ' ' + srgName;
                String hit = resolved.get(key);
                if (hit == null) {
                    hit = findUp(srgOwner, owner -> t.fields.get(owner + ' ' + srgName));
                    resolved.put(key, hit != null ? hit : srgName);
                    if (hit == null)
                        hit = srgName;
                }
                return hit;
        }
    }

    /** Runtime name of a method, looked up from {@code srgOwner} through its super types. */
    public String mapMethod(String srgOwner, String srgName, String srgDesc) {
        if (srgName.startsWith("<"))
            return srgName;
        switch (namespace) {
            case SRG:
                return srgName;
            case MCP:
                return mcpName(srgName);
            default:
                String key = "M " + srgOwner + ' ' + srgName + srgDesc;
                String hit = resolved.get(key);
                if (hit == null) {
                    hit = findUp(srgOwner, owner -> t.methods.get(owner + ' ' + srgName + ' ' + srgDesc));
                    resolved.put(key, hit != null ? hit : srgName);
                    if (hit == null)
                        hit = srgName;
                }
                return hit;
        }
    }

    /** For a lambda implementing a Minecraft interface: the method name without knowing its descriptor. */
    private String mapMethodAnyDesc(String srgOwner, String srgName) {
        if (namespace == Namespace.MCP)
            return mcpName(srgName);
        String hit = findUp(srgOwner, owner -> {
            Set<String> names = t.methodNames.get(owner + ' ' + srgName);
            return names != null && names.size() == 1 ? names.iterator().next() : null;
        });
        return hit != null ? hit : srgName;
    }

    private String mcpName(String srgName) {
        if (!srgName.startsWith("field_") && !srgName.startsWith("func_"))
            return srgName;
        String mcp = t.mcp.get(srgName);
        return mcp != null ? mcp : srgName;
    }

    // ---- runtime -> SRG, for members a class declares itself ----

    /** SRG name of a field declared by {@code srgOwner}, from its runtime name. */
    public String unmapField(String srgOwner, String runtimeName) {
        if (namespace != Namespace.NOTCH)
            return runtimeName;
        String srg = back(true).get(srgOwner + ' ' + runtimeName);
        return srg != null ? srg : runtimeName;
    }

    /** SRG name of a method declared by {@code srgOwner}, from its runtime name and descriptor. */
    public String unmapMethod(String srgOwner, String runtimeName, String runtimeDesc) {
        if (namespace != Namespace.NOTCH)
            return runtimeName;
        String srg = back(false).get(srgOwner + ' ' + runtimeName + ' ' + runtimeDesc);
        return srg != null ? srg : runtimeName;
    }

    private Map<String, String> back(boolean fields) {
        synchronized (t) {
            if (t.fieldsBack == null) {
                Map<String, String> f = new HashMap<>(), m = new HashMap<>();
                for (Map.Entry<String, String> e : t.fields.entrySet()) {
                    String[] k = e.getKey().split(" ");
                    f.put(k[0] + ' ' + e.getValue(), k[1]);
                }
                for (Map.Entry<String, String> e : t.methods.entrySet()) {
                    String[] k = e.getKey().split(" ");
                    m.put(k[0] + ' ' + e.getValue() + ' ' + mapDesc(k[2]), k[1]);
                }
                t.fieldsBack = f;
                t.methodsBack = m;
            }
            return fields ? t.fieldsBack : t.methodsBack;
        }
    }

    // ---- hierarchy ----

    private interface Lookup {
        String find(String owner);
    }

    /** Depth first from owner through its super types (SRG names) for the first hit. */
    private String findUp(String owner, Lookup lookup) {
        return findUp(owner, lookup, new HashSet<>());
    }

    private String findUp(String owner, Lookup lookup, Set<String> seen) {
        if (owner == null || owner.startsWith("[") || owner.startsWith("java/") || !seen.add(owner))
            return null;
        String hit = lookup.find(owner);
        if (hit != null)
            return hit;
        for (String parent : supers(owner)) {
            hit = findUp(parent, lookup, seen);
            if (hit != null)
                return hit;
        }
        return null;
    }

    private String[] supers(String owner) {
        String[] known = t.supers.get(owner);
        if (known != null)
            return known;
        // a client class (or an addon's) extending a Minecraft class: read its class file
        String[] cached = otherSupers.get(owner);
        if (cached != null)
            return cached;
        String[] result = new String[0];
        byte[] bytes = loader != null ? read(loader, owner + ".class") : null;
        if (bytes != null) {
            ClassReader reader = new ClassReader(bytes);
            String[] ifaces = reader.getInterfaces();
            result = new String[ifaces.length + 1];
            result[0] = reader.getSuperName();
            System.arraycopy(ifaces, 0, result, 1, ifaces.length);
        }
        otherSupers.put(owner, result);
        return result;
    }

    /** Remembers the super types of a class that has no class file to read (a freshly compiled addon). */
    public void registerSupers(byte[] classBytes) {
        ClassReader reader = new ClassReader(classBytes);
        String[] ifaces = reader.getInterfaces();
        String[] result = new String[ifaces.length + 1];
        result[0] = reader.getSuperName();
        System.arraycopy(ifaces, 0, result, 1, ifaces.length);
        otherSupers.put(reader.getClassName(), result);
    }

    static byte[] read(ClassLoader loader, String path) {
        try (InputStream in = loader.getResourceAsStream(path)) {
            if (in == null)
                return null;
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buf = new byte[8192];
            int n;
            while ((n = in.read(buf)) != -1)
                out.write(buf, 0, n);
            return out.toByteArray();
        } catch (Exception e) {
            return null;
        }
    }

    // ---- class files ----

    /**
     * Renames the Minecraft references in a class of the client (or a compiled addon) from SRG to runtime names.
     * @return the same array when nothing needs renaming
     */
    public byte[] toRuntime(byte[] classBytes) {
        if (namespace == Namespace.SRG || !contains(classBytes, MC_BYTES))
            return classBytes;
        ClassReader reader = new ClassReader(classBytes);
        ClassWriter writer = new ClassWriter(0);
        reader.accept(new RemappingClassAdapter(writer, new Remapper() {
            @Override
            public String map(String typeName) {
                return mapClass(typeName);
            }

            @Override
            public String mapFieldName(String owner, String name, String desc) {
                return owner.startsWith("[") ? name : mapField(owner, name);
            }

            @Override
            public String mapMethodName(String owner, String name, String desc) {
                return owner.startsWith("[") ? name : mapMethod(owner, name, desc);
            }

            @Override
            public String mapInvokeDynamicMethodName(String name, String desc) {
                Type made = Type.getReturnType(desc);
                if (made.getSort() == Type.OBJECT && made.getInternalName().startsWith(MC))
                    return mapMethodAnyDesc(made.getInternalName(), name);
                return name;
            }
        }), ClassReader.EXPAND_FRAMES); // the remapping method adapter sorts locals, which needs expanded frames
        return writer.toByteArray();
    }

    /**
     * The declarations of a vanilla (notch) class with SRG names, for compiling addons against. Method bodies are
     * dropped; only the shape of the class is needed.
     */
    public byte[] toSrgDeclarations(byte[] runtimeBytes) {
        if (namespace != Namespace.NOTCH)
            return runtimeBytes;
        ClassReader reader = new ClassReader(runtimeBytes);
        ClassWriter writer = new ClassWriter(0);
        Remapper remapper = new Remapper() {
            @Override
            public String map(String typeName) {
                return unmapClass(typeName);
            }

            @Override
            public String mapFieldName(String owner, String name, String desc) {
                return unmapField(unmapClass(owner), name);
            }

            @Override
            public String mapMethodName(String owner, String name, String desc) {
                return name.startsWith("<") ? name : unmapMethod(unmapClass(owner), name, desc);
            }
        };
        ClassVisitor innerNames = new ClassVisitor(Opcodes.ASM5, writer) {
            @Override
            public void visitInnerClass(String name, String outerName, String innerName, int access) {
                // the remapper renames the inner class but not its simple name, which the compiler reads
                if (innerName != null) {
                    int dollar = name.lastIndexOf('$');
                    if (dollar >= 0 && dollar + 1 < name.length() && !Character.isDigit(name.charAt(dollar + 1)))
                        innerName = name.substring(dollar + 1);
                }
                super.visitInnerClass(name, outerName, innerName, access);
            }
        };
        reader.accept(new RemappingClassAdapter(innerNames, remapper), ClassReader.SKIP_CODE | ClassReader.SKIP_FRAMES);
        return writer.toByteArray();
    }

    private static boolean contains(byte[] haystack, byte[] needle) {
        outer:
        for (int i = 0; i <= haystack.length - needle.length; i++) {
            for (int j = 0; j < needle.length; j++)
                if (haystack[i + j] != needle[j])
                    continue outer;
            return true;
        }
        return false;
    }
}
